### ISSUE TITLE
Any way to comment IP in the servers file ?

### ISSUE THREAD

**Issue by matlink** [bearstech/pussh#1]
When I use the -f option, I'd like to have a file that contains all of my servers, but with some of them being commented out with # for example.
Is that already possible or should I hack this tool and make a PR ?

**Comment by zerodeux** [comment]
It's not possible but that would be a nice hack (a |grep -v '^#' would
do I guess), PR welcome.

**Comment by zerodeux** [comment]
Was implemented in pussh 1.2 3 years ago (https://github.com/bearstech/pussh/commit/ccf197b56601da7f4195fac51ec8d77a1e1fe827).

Also ignored empty lines (including whitespaces) in https://github.com/bearstech/pussh/commit/17f57fa181e2236cae3a737d10a71d802d97a73a
