### ISSUE TITLE
Portability for macOS

### ISSUE THREAD

**Issue by majal** [bearstech/pussh#10]
My wife uses a MacBook, and I've been trying it out. Running `pussh` on macOS (Sonoma) does not work out of the box. The issue is the kind of `bash` that ships with MacOS is kinda different. To make my bash scripts work, I needed to install the `bash` version of [Homebrew](https://brew.sh/).

To use the custom version of `bash`, I had to set my shell to use the non-default `bash` and change my script's shebang to refer to whatever bash my shell is using. My shebang was changed from `#!/bin/bash` to `#!/usr/bin/env bash`.

There's much debate as to [which shebang is better](https://stackoverflow.com/questions/21612980). But it seems that the latter is better for portability.

For `pussh`, the shebang `#!/bin/bash -e` results to this error on otherwise valid commands:

```
/Users/mac/bin/pussh: line 186: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

Changing that shebang to `#!/usr/bin/env bash -e` makes it work on macOS systems.

**Comment by zerodeux** [comment]
It's true that `/usr/bin/env bash` is more portable, and I expect `pussh` to be portable.

And AFAIK if it works somewhere with `/bin/bash` it should also work with `/usr/bin/env bash`, so no regression expected.

I didn't know about the MacOS situation, it seems that they keep distributing an old Bash 3.x as a default, whereas associative arrays in Bash only appeared in 4.x (released in feb. 2009, well...). I won't support Bash 3.x :)

**Comment by zerodeux** [comment]
Suggestion applied, pussh 1.4 released with it. Thanks @majal !

**Comment by majal** [comment]
Thank you for this useful tool @zerodeux, and for your quick response.
