### ISSUE TITLE
pussh -f hosts.txt 'finger | wc -l' not working

### ISSUE THREAD

**Issue by navoj** [bearstech/pussh#5]
I'm running pussh on MobaXTerm's cygwin bash version 4.1.17(0). I'm trying to list the number of users on my servers but I get a command not found error when I try the command:

pussh -f hosts.txt 'finger | wc -l'

Is this a cygwin specific problem?

**Comment by zerodeux** [comment]
Does pussh work correctly ? Try:
- single host : pussh -h host true
- multiple hosts: pussh -f hosts.txt true

If that's the case, that's probably failing on the remote side.
