### ISSUE TITLE
How to chain multiple commands?

### ISSUE THREAD

**Issue by majal** [bearstech/pussh#7]
I regularly run chained ssh commands, i.e.

`ssh uname@host 'command1; command2 && command3 || command4'`

Is there a way to do this in `pussh`?

(I tried it but it seems commands break whenever they are inside quotes.)

**Comment by Mickael-Martin** [comment]
Hi,
Use -u option with script. You can transfert and execute what you want.

**Comment by majal** [comment]
I see. Thank you @Mickael-Martin.

So it means upload. Do I need to create a new file? Or will the shell command `<(echo "commands")` work?

**Comment by Mickael-Martin** [comment]
Please, read the README. You can find `$ pussh -f servers -u my-deploy.sh args ...`
You write the script on the "master", pussh upload and execute on remote.

**Comment by majal** [comment]
Thank you. I was really hoping not needing to write a script for some of these simple chained commands. But well, if there is no other way, we can do that too. 🙂

**Comment by Mickael-Martin** [comment]
You can use "bash -c 'cmd'" maybe ?

**Comment by majal** [comment]
You know what? That worked. 😄

I just had to remove the external quotes, because it didn't work with quotes.

This one worked for me:

```
pussh -h $(echo user@{1..20}.domain, | tr -d ' ') bash -c 'cd ~/folder; command1 && command2 || command3'
```

Thanks for the help @Mickael-Martin!

**Comment by zerodeux** [comment]
Thanks @Mickael-Martin for helping @majal
